name: upload


on:
  - push


jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@main


      - name: Upload file via SSH
        uses: nicklasfrahm/scp-action@main
        with:
          direction: upload
          host: 3.215.39.35
          username: ubuntu
          fingerprint: bd:1d:03:b2:11:0f:98:ed:41:95:36:76:d6:4e:bd:f1:97
          key: 'DemoWebAppSC\key\ls-rywds-dev-01-keypair-01.pem'
          port: 22
          source: './publish/'
          target: /usr/devscapps/pomodoro/

    





   